name: wholewheattoast
description: Personal website of shawn eisenach
author: shawn eisenach
author_email: shawn@wholewheattoast.com

# Serving
production: false
port:    4000
#host:    0.0.0.0
baseurl:
url: http://www.wholewheattoast.com

# Outputting
permalink:     date
paginate_path: /page:num
timezone: America/Los_Angeles

## Where things are
#source:      .
destination: _site/
plugins_dir:     _plugins/
includes:    _includes/

## Handling Reading
safe:        false
include:      [".htaccess"]
exclude: [sass, README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## Filtering Content
#future:      false
show_drafts: null
limit_posts: 0
#permalink:   pretty
paginate:    5

# Plugins
whitelist: []
gems:      [jekyll-paginate]

# Conversion
markdown:    rdiscount
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

rdiscount:
  extensions: []
