name: wholewheattoast
description: Personal website of shawn eisenach
author: shawn eisenach
author_email: shawn@wholewheattoast.com

# Serving
production: false
port:    4000
#host:    0.0.0.0
baseurl:
url: http://www.wholewheattoast.com
incremental: true

# Outputting
# permalink:     date
# Produces a cleaner folder structure when using categories
permalink: /:year/:month/:title.html
timezone: America/Los_Angeles

## Where things are
#source:      .
destination: _site/
plugins_dir: _plugins/
includes:    _includes/

## Handling Reading
safe:        false
include:      [".htaccess"]
exclude: [sass, README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

## Filtering Content
#future:      false
show_drafts: null
limit_posts: 0

# Plugins
whitelist: []
# gems:      [jekyll-paginate]
plugins:
  - jekyll-paginate-v2

# Conversion
markdown:    rdiscount
highlighter: pygments
lsi:         false
excerpt_separator: "\n\n"

rdiscount:
  extensions: []
  
  
# Pagination Settings
pagination:
  enabled: true
  per_page: 5
  permalink: '/page/:num/'
  title: ':title - page :num of :max'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
